# Generated by Django 4.0.4 on 2022-06-11 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_width', models.CharField(max_length=100)),
                ('product_hight', models.CharField(max_length=100)),
                ('product_depth', models.CharField(max_length=100)),
                ('product_weight', models.CharField(max_length=100)),
                ('product_pic', models.ImageField(upload_to='prouct_pic')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
