# Generated by Django 4.0.4 on 2022-06-12 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
