# Generated by Django 4.0.4 on 2022-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='statud',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
