# Generated by Django 4.0.4 on 2022-06-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_statud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='statud',
            new_name='status',
        ),
    ]
