# Generated by Django 4.0.4 on 2022-06-13 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_statud_cart_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_total',
            new_name='total_price',
        ),
    ]
